//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCInventory.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Device
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Device()
        {
            this.DeviceDroping = new HashSet<DeviceDroping>();
            this.DeviceMoving = new HashSet<DeviceMoving>();
        }
    
        public int DeviceID { get; set; }
        public string DeviceName { get; set; }
        public int DeviceTypeID { get; set; }
        public string DeviceModel { get; set; }
        public string DeviceInventNum { get; set; }
        public string DeviceSerialNum { get; set; }
        public System.DateTime DeviceDatePurchase { get; set; }
        public decimal DevicePrice { get; set; }
        public int DeviceStatusID { get; set; }
        public Nullable<int> PlaceInstallID { get; set; }
    
        public virtual DeviceStatus DeviceStatus { get; set; }
        public virtual DeviceType DeviceType { get; set; }
        public virtual PlaceInstall PlaceInstall { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeviceDroping> DeviceDroping { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeviceMoving> DeviceMoving { get; set; }
    }
}
